[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
runner = """qemu-system-riscv64
 -machine virt -d guest_errors,unimp
 -smp 1 -m 128M
 -nographic
 -serial mon:stdio
 -bios ../third-party/rustsbi-qemu/target/riscv64imac-unknown-none-elf/release/rustsbi-qemu.bin
 -S -s
 -kernel
"""
rustflags = [
    "-Clink-arg=-Tsrc/kernel.ld", "-Cforce-frame-pointers=yes", "-Zemit-stack-sizes"
]